services:
  - type: web
    name: gdm-web
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: gdm.settings
      - key: PYTHON_VERSION
        value: 3.11
    autoDeploy: true

staticPublishPath: staticfiles
