services:
  - type: web
    name: gdm-mvp
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn gdm.wsgi:application
    staticPublishPath: staticfiles
    routes:
      - type: web
        path: /
      - type: static
        path: /static
        directory: staticfiles
staticSites:
  - name: static
    staticPublishPath: staticfiles
    urlPath: /static
