# Generated by Django 4.2.23 on 2025-07-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='fitbit_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
