# Generated by Django 4.2.23 on 2025-09-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='status_flags',
            field=models.JSONField(blank=True, default=dict, help_text='Flexible status and error flags for sync, auth, etc.'),
        ),
    ]
