# Generated by Django 4.2.23 on 2025-10-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_participant_status_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='daily_wear_time',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='participant',
            name='daily_steps',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
