# Generated by Django 4.2.23 on 2025-08-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_participant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='google_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
