# Generated by Django 4.2.23 on 2025-08-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_participant_google_email_participant_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='google_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='google_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='google_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
