# Generated by Django 4.2.23 on 2025-08-30 13:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_participant_google_email_participant_google_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='google_email',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='google_id',
        ),
        migrations.CreateModel(
            name='DeviceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=50)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires', models.DateTimeField(blank=True, null=True)),
                ('auth_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('device_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('device_data', models.JSONField(blank=True, default=dict)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_accounts', to='core.participant')),
            ],
            options={
                'unique_together': {('participant', 'device_type')},
            },
        ),
    ]
