# Generated by Django 4.2.23 on 2025-10-03 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_participant_daily_wear_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='daily_wear_time',
        ),
    ]
