# Generated by Django 4.2.23 on 2025-09-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_participant_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='message_history',
            field=models.JSONField(blank=True, default=list, help_text='History of messages sent to participant'),
        ),
    ]
