# Generated by Django 4.2.23 on 2025-10-07 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_participant_daily_wear_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='fitbit_user_id',
            field=models.CharField(blank=True, default='temp', help_text="Required: Participant's Fitbit User ID (6 characters, found in Fitbit app: You > Edit Profile)", max_length=6, validators=[django.core.validators.RegexValidator(message='Fitbit User ID must be exactly 6 alphanumeric characters', regex='^[A-Za-z0-9]{6}$')]),
            preserve_default=False,
        ),
    ]
