# Generated by Django 4.2.23 on 2025-09-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_participant_google_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='device_type',
            field=models.CharField(choices=[('fitbit', 'Fitbit'), ('garmin', 'Garmin')], default='fitbit', max_length=20),
        ),
        migrations.AddField(
            model_name='participant',
            name='garmin_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='garmin_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='garmin_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='garmin_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
