# Generated by Django 4.2.23 on 2025-09-02 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_participant_google_access_token_and_more'),
        ('core', '0005_participant_device_type_and_more'),
    ]

    operations = [
    ]
