# Generated by Django 4.2.23 on 2025-10-31 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_participant_fitbit_user_id'),
    ]

    operations = [
    ]
