# Generated by Django 4.2.23 on 2025-10-31 17:13
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_alter_participant_fitbit_user_id'),
    ]
    
    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TABLE core_participant_fitbit_token_history (
                    id SERIAL PRIMARY KEY,
                    participant_id INT NOT NULL,
                    old_refresh_token TEXT,
                    new_refresh_token TEXT,
                    changed_at TIMESTAMPTZ DEFAULT now(),
                    CONSTRAINT fk_core_participant 
                        FOREIGN KEY (participant_id) 
                        REFERENCES core_participant(id) 
                        ON DELETE CASCADE
                );

                CREATE INDEX idx_core_participant_token_history_participant_id 
                    ON core_participant_fitbit_token_history(participant_id);

                CREATE INDEX idx_core_participant_token_history_changed_at 
                    ON core_participant_fitbit_token_history(changed_at DESC);

                CREATE OR REPLACE FUNCTION log_fitbit_token_changes()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF OLD.fitbit_refresh_token IS DISTINCT FROM NEW.fitbit_refresh_token THEN
                        INSERT INTO core_participant_fitbit_token_history(
                            participant_id, 
                            old_refresh_token, 
                            new_refresh_token
                        )
                        VALUES (
                            OLD.id, 
                            OLD.fitbit_refresh_token, 
                            NEW.fitbit_refresh_token
                        );
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER fitbit_token_history_trigger
                AFTER UPDATE ON core_participant
                FOR EACH ROW
                EXECUTE FUNCTION log_fitbit_token_changes();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS fitbit_token_history_trigger ON core_participant;
                DROP FUNCTION IF EXISTS log_fitbit_token_changes();
                DROP TABLE IF EXISTS core_participant_fitbit_token_history;
            """
        ),
    ]