# Generated by Django 4.2.23 on 2025-09-02 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_merge_20250902_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='garmin_access_token',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='garmin_refresh_token',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='garmin_token_expires',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='garmin_user_id',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='google_access_token',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='google_refresh_token',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='google_token_expiry',
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DeviceAccount',
        ),
    ]
