# Generated by Django 4.2.23 on 2025-11-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_fitbit_token_history_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='device_sync_status',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
