# Generated by Django 4.2.23 on 2025-09-02 18:49

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_participant_device_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='device_type',
            field=models.CharField(
                max_length=50,
                default='fitbit',  # hard-coded default for migration safety
            ),
        ),
    ]
