# Generated by Django 4.2.23 on 2025-03-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_participant_device_sync_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='treatment_arm',
            field=models.IntegerField(choices=[(0, 'Control'), (1, 'Intervention')], default=0, help_text='Treatment arm assignment: 0=Control, 1=Intervention'),
            preserve_default=False,
        ),
    ]
