# Generated by Django 4.2.23 on 2025-09-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_device_type_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='height',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='weight',
        ),
    ]
