# Generated by Django 4.2.23 on 2025-09-10 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_add_device_type_back'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('average_steps', models.IntegerField()),
                ('increase', models.CharField(max_length=50)),
                ('new_target', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_goals', to='core.participant')),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('participant', 'week_start')},
            },
        ),
    ]
