# Generated by Django 4.2.23 on 2025-08-01 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_integration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FitbitAccount',
        ),
    ]
